In [1]:
import pandas as pd
import numpy as np
import sklearn

In [73]:
# To upload files via google colab
# from google.colab import files
# file1 = files.upload
# then a choose file button will appear
# choose the file from your system and select ok.
# After that in the left sidebar you will see a file manager icon...click on it
# There you will see the file you upladed just now.
# Click on the three dots and then on Copy path option.
# past that path in the 
# df = pd.read_csv("**copied path**")

In [1]:
df=pd.read_csv("csv_data.csv")

NameError: name 'pd' is not defined

In [75]:
# Exercise cise 1 : Classroom Exercise 3

In [54]:
df.head()

A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   4.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [55]:
df.tail()

A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   4.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [56]:
print(df)

    A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   4.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN


In [57]:
arr=np.array(df)

In [58]:
print(arr)

[[10. 20. 30. 40.]
 [ 1.  2. nan  4.]
 [ 5.  6. nan  8.]
 [ 0. 11. 12. nan]]


In [76]:
df.isnull().sum() #missing values in each column

A    0
B    0
C    2
D    1
dtype: int64

In [60]:
df.isnull().sum().sum() # sum of all the missing values

3

In [77]:
# Exercise 2 : Classroom Exercise 3

In [61]:
df.dropna(axis=0) # drop rows with missing values

A   B     C     D
0  10  20  30.0  40.0

In [62]:
print(df)

    A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   4.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN


In [78]:
df.dropna(axis=1) # Drop the columns with missing values

A   B
0  10  20
1   1   2
2   5   6
3   0  11

In [64]:
df.dropna(axis=0, how='any') # drop rows having null value in any column

A   B     C     D
0  10  20  30.0  40.0

In [65]:
df.dropna(axis=0, how='all') # drop rows having null values in all the columns

A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   4.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [79]:
df.dropna(axis=0, thresh=2) # leave the row where atleast 2 values are not null
# drop the rest

A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   4.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [80]:
df.dropna(axis=0, thresh=4) # leave the row where atleast 4 values are not null
# drop the rest

A   B     C     D
0  10  20  30.0  40.0

In [68]:
df.dropna(axis=0, subset=['C']) # drop the rows where null values
# are in clumn C

A   B     C     D
0  10  20  30.0  40.0
3   0  11  12.0   NaN

In [81]:
# Exercise 3 : Classroom Exercise 3

In [69]:
from sklearn.impute import SimpleImputer

In [70]:
# Replacing missing values using mean imputer
s1=SimpleImputer(strategy='mean')

# Replacing missing values using median imputer
s2=SimpleImputer(strategy='median')

In [71]:
s1.fit_transform(df)

array([[10.        , 20.        , 30.        , 40.        ],
       [ 1.        ,  2.        , 21.        ,  4.        ],
       [ 5.        ,  6.        , 21.        ,  8.        ],
       [ 0.        , 11.        , 12.        , 17.33333333]])

In [72]:
s2.fit_transform(df)

array([[10., 20., 30., 40.],
       [ 1.,  2., 21.,  4.],
       [ 5.,  6., 21.,  8.],
       [ 0., 11., 12.,  8.]])