In [1]:
import numpy as np

In [71]:
x = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])

In [72]:
target = np.array([0,0,0,0,1,1,1,1])

In [73]:
w = np.array([1,-1,-1])
b = -0.5

In [74]:
def perceptron(x,w,b):
    y = np.sum(x*w)+b
    if y>0:
        return 1
    else:
        return 0

In [75]:
output = []
for i in range(x.shape[0]):
    output.append(perceptron(x[i],w,b))

In [76]:
output

[0, 0, 0, 0, 1, 0, 0, 0]

In [77]:
correct = 0
for i in range(8):
    if target[i] == output[i]:
        correct += 1
accuracy = correct/8
print("Accuracy : ",accuracy)

Accuracy :  0.625


In [78]:
tp = 0
tn = 0
fp = 0
fn = 0

In [79]:
for i in range(8):
    if target[i]==output[i] == 0:
        tp += 1
    elif target[i] == output[i] == 1:
        tn += 1
    elif target[i] == 1 and output[i] == 0:
        fp +=1
    else:
        fn += 1
print("True Positive : ",tp)
print("False Positive : ",fp)
print("True Negative : ",tn)
print("False Negative : ",fn)

True Positive :  4
False Positive :  3
True Negative :  1
False Negative :  0


In [80]:
precision = tp/(tp + fp)
recall = tp/(tp + fn)
f1_score = (2 * precision * recall)/(precision + recall)

In [81]:
print("Precision : ",precision)
print("Recall : ",recall)
print("F1-Score : ",f1_score)

Precision :  0.5714285714285714
Recall :  1.0
F1-Score :  0.7272727272727273


In [82]:
x1 = np.arange(1,11)
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
x1.shape

(10,)

In [84]:
test_size = 0.20

In [85]:
no_ele = int(x1.shape[0]*(test_size))
no_ele

2

In [86]:
train_size = 10-no_ele
train_data = x1[:train_size]
test_data = x1[train_size:]

In [87]:
train_data

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
test_data

array([ 9, 10])