In [1]:
from sklearn.datasets import load_iris

In [2]:
x=load_iris().data

In [3]:
y=load_iris().target

In [4]:
x.shape

(150, 4)

In [5]:
y.shape

(150,)

In [6]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [7]:
import pandas as pd

In [8]:
pd.DataFrame(x).isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [9]:
pd.DataFrame(x).head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_x, test_x, train_y, test_y=train_test_split(x,y, test_size=(0.3))

In [12]:
train_x.shape

(105, 4)

In [13]:
test_x.shape

(45, 4)

In [14]:
pd.DataFrame(train_x).describe()

0           1           2           3
count  105.000000  105.000000  105.000000  105.000000
mean     5.900952    3.050476    3.812381    1.220952
std      0.825960    0.450667    1.736193    0.746362
min      4.400000    2.000000    1.000000    0.100000
25%      5.200000    2.800000    1.600000    0.400000
50%      5.800000    3.000000    4.300000    1.300000
75%      6.500000    3.400000    5.100000    1.800000
max      7.900000    4.400000    6.700000    2.500000

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc=StandardScaler()

In [17]:
train_x_sc=sc.fit_transform(train_x)

In [18]:
pd.DataFrame(train_x_sc).describe()

0             1             2             3
count  1.050000e+02  1.050000e+02  1.050000e+02  1.050000e+02
mean   1.078502e-15 -1.205121e-15  2.135858e-16 -6.948146e-16
std    1.004796e+00  1.004796e+00  1.004796e+00  1.004796e+00
min   -1.825936e+00 -2.342116e+00 -1.627625e+00 -1.509091e+00
25%   -8.527216e-01 -5.584556e-01 -1.280383e+00 -1.105214e+00
50%   -1.228104e-01 -1.125405e-01  2.822024e-01  1.064185e-01
75%    7.287526e-01  7.792898e-01  7.451908e-01  7.795474e-01
max    2.431879e+00  3.008866e+00  1.671168e+00  1.721928e+00

In [19]:
from sklearn.linear_model import Perceptron

In [20]:
p=Perceptron()
p.fit(train_x_sc,train_y)

Perceptron()

In [21]:
test_pred=p.predict(test_x)
train_pred=p.predict(train_x_sc)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
print("Training Accuracy: ", accuracy_score(train_y, train_pred ))

Training Accuracy:  0.9047619047619048


In [24]:
print("Testing Accuracy: ", accuracy_score(test_y, test_pred))

Testing Accuracy:  0.37777777777777777


In [25]:
p1=Perceptron(penalty='l1')

In [26]:
p1.fit(train_x_sc,train_y)

Perceptron(penalty='l1')

In [27]:
train_pred_l1=p1.predict(train_x_sc)
test_pred_l1=p1.predict(test_x)

In [28]:
print("Training Accuracy: ", accuracy_score(train_y, train_pred_l1 ))

Training Accuracy:  0.9619047619047619


In [29]:
print("Testing Accuracy: ", accuracy_score(test_y, test_pred_l1))

Testing Accuracy:  0.37777777777777777


In [30]:
p2=Perceptron(penalty='l2')

In [31]:
p2.fit(train_x_sc,train_y)

Perceptron(penalty='l2')

In [32]:
train_pred_l2=p2.predict(train_x_sc)
test_pred_l2=p2.predict(test_x)

In [33]:
print("Training Accuracy: ", accuracy_score(train_y, train_pred_l2 ))

Training Accuracy:  0.9619047619047619


In [34]:
print("Testing Accuracy: ", accuracy_score(test_y, test_pred_l2))

Testing Accuracy:  0.37777777777777777


In [35]:
p3=Perceptron(penalty='elasticnet', alpha=0.1)

In [36]:
p3.fit(train_x_sc,train_y)

Perceptron(alpha=0.1, penalty='elasticnet')

In [37]:
train_pred_l3=p2.predict(train_x_sc)
test_pred_l3=p2.predict(test_x)

In [38]:
print("Training Accuracy: ", accuracy_score(train_y, train_pred_l3 ))

Training Accuracy:  0.9619047619047619


In [39]:
print("Testing Accuracy: ", accuracy_score(test_y, test_pred_l3))

Testing Accuracy:  0.37777777777777777


In [40]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, precision_recall_curve

In [41]:
print(confusion_matrix(test_y, test_pred_l2))

[[ 0  0 17]
 [ 0  0 11]
 [ 0  0 17]]


In [42]:
reg=['l1', 'l2', 'elasticnet']
C=[0.001, 0.01, 0.1, 1]

In [43]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'

In [44]:
import pandas as pd

In [45]:
df=pd.read_csv(url, header=None, na_values=' ?')

In [46]:
df.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [47]:
df.isnull().sum()

0        0
1     1836
2        0
3        0
4        0
5        0
6     1843
7        0
8        0
9        0
10       0
11       0
12       0
13     583
14       0
dtype: int64

In [48]:
from sklearn.impute import SimpleImputer

In [49]:
si=SimpleImputer(strategy='most_frequent')

In [50]:
df=si.fit_transform(df)

In [51]:
pd.DataFrame(df).isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
dtype: int64

In [52]:
cols=[1,3, 5,6,7,8,9,13, 14]

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
le=LabelEncoder()

In [55]:
df=pd.DataFrame(df)

In [56]:
for i in cols:
  df[i]=le.fit_transform(df[i])

In [57]:
df.head()

0   1       2   3   4   5   6   7   8   9     10 11  12  13  14
0  39   6   77516   9  13   4   0   1   4   1  2174  0  40  38   0
1  50   5   83311   9  13   2   3   0   4   1     0  0  13  38   0
2  38   3  215646  11   9   0   5   1   4   1     0  0  40  38   0
3  53   3  234721   1   7   2   5   0   2   1     0  0  40  38   0
4  28   3  338409   9  13   2   9   5   2   0     0  0  40   4   0

In [58]:
y=df[14]

In [59]:
y.shape

(32561,)

In [60]:
x=df.drop(columns=14)

In [61]:
x.shape

(32561, 14)

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
train_x, test_x, train_y, test_y=train_test_split(x,y, test_size=0.3)

In [64]:
train_x.shape

(22792, 14)

In [65]:
test_x.shape

(9769, 14)

In [66]:
train_x.describe()

1             3             5             6             7   \
count  22792.000000  22792.000000  22792.000000  22792.000000  22792.000000   
mean       3.098324     10.296244      2.612627      6.150184      1.441471   
std        1.116776      3.876770      1.503172      3.967414      1.610209   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        3.000000      9.000000      2.000000      3.000000      0.000000   
50%        3.000000     11.000000      2.000000      7.000000      1.000000   
75%        3.000000     12.000000      4.000000      9.000000      3.000000   
max        7.000000     15.000000      6.000000     13.000000      5.000000   

                 8             9            13  
count  22792.000000  22792.000000  22792.00000  
mean       3.665804      0.670411     36.43252  
std        0.846144      0.470074      6.02316  
min        0.000000      0.000000      0.00000  
25%        4.000000      0.000000     38.00000  
50%        4.000000      1.000000     38.00000  
75%        4.000000      1.000000     38.00000  
max        4.000000      1.000000     40.00000

In [67]:
from sklearn.preprocessing import StandardScaler

In [68]:
sc=StandardScaler()

In [69]:
train_x_sc=sc.fit_transform(train_x)

In [70]:
pd.DataFrame(train_x_sc).describe()

0             1             2             3             4   \
count  2.279200e+04  2.279200e+04  2.279200e+04  2.279200e+04  2.279200e+04   
mean   1.224584e-16 -1.405083e-16 -7.871711e-18  8.029340e-16 -9.016422e-18   
std    1.000022e+00  1.000022e+00  1.000022e+00  1.000022e+00  1.000022e+00   
min   -1.592862e+00 -2.774409e+00 -1.693512e+00 -2.655941e+00 -3.530694e+00   
25%   -7.867286e-01 -8.804466e-02 -6.843032e-01 -3.343693e-01 -4.204259e-01   
50%   -1.271649e-01 -8.804466e-02 -1.074248e-01  1.815355e-01 -3.164239e-02   
75%    6.789685e-01 -8.804466e-02  4.535112e-01  4.394878e-01  7.459246e-01   
max    3.756932e+00  3.493774e+00  1.127923e+01  1.213345e+00  2.301058e+00   

                 5             6             7             8             9   \
count  2.279200e+04  2.279200e+04  2.279200e+04  2.279200e+04  2.279200e+04   
mean  -7.916233e-16  2.757583e-16  9.352528e-17  4.547862e-16 -5.284958e-16   
std    1.000022e+00  1.000022e+00  1.000022e+00  1.000022e+00  1.000022e+00   
min   -1.738114e+00 -1.550208e+00 -8.952266e-01 -4.332460e+00 -1.426211e+00   
25%   -4.075651e-01 -7.940319e-01 -8.952266e-01  3.949725e-01 -1.426211e+00   
50%   -4.075651e-01  2.142036e-01 -2.741757e-01  3.949725e-01  7.011584e-01   
75%    9.229834e-01  7.183213e-01  9.679260e-01  3.949725e-01  7.011584e-01   
max    2.253532e+00  1.726557e+00  2.210028e+00  3.949725e-01  7.011584e-01   

                 10            11            12            13  
count  2.279200e+04  2.279200e+04  2.279200e+04  2.279200e+04  
mean   9.571558e-16 -4.522147e-15  2.873272e-16 -2.210704e-15  
std    1.000022e+00  1.000022e+00  1.000022e+00  1.000022e+00  
min   -1.463648e-01 -2.130920e-01 -3.203258e+00 -6.048872e+00  
25%   -1.463648e-01 -2.130920e-01 -4.067052e-02  2.602478e-01  
50%   -1.463648e-01 -2.130920e-01 -4.067052e-02  2.602478e-01  
75%   -1.463648e-01 -2.130920e-01  3.647894e-01  2.602478e-01  
max    1.333958e+01  1.073453e+01  4.743757e+00  5.923067e-01

In [71]:
from sklearn.linear_model import Perceptron

In [72]:
p=Perceptron()

In [73]:
p.fit(train_x_sc, train_y)

Perceptron()

In [74]:
train_pred=p.predict(train_x_sc)
test_pred=p.predict(test_x)

In [75]:
print("Training Accuracy: ", accuracy_score(train_pred, train_y))
print("Testing Accuracy: ", accuracy_score(test_pred, test_y))

Training Accuracy:  0.7604861354861355
Testing Accuracy:  0.23523390316306683


In [76]:
p_l1=Perceptron(penalty='l1')

In [77]:
p_l1.fit(train_x_sc, train_y)

Perceptron(penalty='l1')

In [78]:
train_pred_l1=p_l1.predict(train_x_sc)
test_pred_l1=p_l1.predict(test_x)

In [79]:
print("Training Accuracy: ", accuracy_score(train_pred_l1, train_y))
print("Testing Accuracy: ", accuracy_score(test_pred_l1, test_y))

Training Accuracy:  0.7641716391716392
Testing Accuracy:  0.23523390316306683


In [80]:
p_l2=Perceptron(penalty='l2')
p_l2.fit(train_x_sc, train_y)
train_pred_l2=p_l2.predict(train_x_sc)
test_pred_l2=p_l2.predict(test_x)
print("Training Accuracy: ", accuracy_score(train_pred_l2, train_y))
print("Testing Accuracy: ", accuracy_score(test_pred_l2, test_y))

Training Accuracy:  0.7503071253071253
Testing Accuracy:  0.23523390316306683


In [81]:
from sklearn.linear_model import LogisticRegression

In [82]:
lr=LogisticRegression(penalty='none')

In [83]:
lr.fit(train_x_sc, train_y)

LogisticRegression(penalty='none')

In [84]:
train_pred_lr=lr.predict(train_x_sc)
test_pred_lr=lr.predict(test_x)

In [85]:
print("Training Accuracy: ", accuracy_score(train_pred_lr, train_y))
print("Testing Accuracy: ", accuracy_score(test_pred_lr, test_y))

Training Accuracy:  0.8245436995436995
Testing Accuracy:  0.23523390316306683


# Support Vector Machine

In [86]:
from sklearn.svm import SVC

In [87]:
df.head()

0   1       2   3   4   5   6   7   8   9     10 11  12  13  14
0  39   6   77516   9  13   4   0   1   4   1  2174  0  40  38   0
1  50   5   83311   9  13   2   3   0   4   1     0  0  13  38   0
2  38   3  215646  11   9   0   5   1   4   1     0  0  40  38   0
3  53   3  234721   1   7   2   5   0   2   1     0  0  40  38   0
4  28   3  338409   9  13   2   9   5   2   0     0  0  40   4   0

In [88]:
train_x_sc.shape

(22792, 14)

In [91]:
test_x.shape

(9769, 14)

In [90]:
train_y.shape

(22792,)

In [93]:
test_y.shape

(9769,)

In [117]:
svc = SVC(C = 0.1)

In [118]:
svc.fit(train_x_sc,train_y)

SVC(C=0.1)

In [119]:
train_pred_svc = svc.predict(train_x_sc)
test_pred_svc = svc.predict(test_x)

In [120]:
print("Training Accuracy : ", accuracy_score(train_pred_svc,train_y))
print("Testing Accuracy : ",accuracy_score(test_pred_svc,test_y))

Training Accuracy :  0.840952965952966
Testing Accuracy :  0.7647660968369332


In [100]:
svc1 = SVC(kernel = "linear",C = 0.5)

In [102]:
svc1.fit(train_x_sc,train_y)

SVC(C=0.5, kernel='linear')

In [103]:
train_pred_svc1 = svc1.predict(train_x_sc)
test_pred_svc1 = svc1.predict(test_x)

In [104]:
print("Training Accuracy : ", accuracy_score(train_pred_svc1,train_y))
print("Testing Accuracy : ",accuracy_score(test_pred_svc1,test_y))

Training Accuracy :  0.8152421902421902
Testing Accuracy :  0.23523390316306683


In [106]:
#Overfitted, So data is not linearly separable here

In [113]:
svc2 = SVC(kernel = "poly",C = 10)

In [114]:
svc2.fit(train_x_sc,train_y)

SVC(C=10, kernel='poly')

In [115]:
train_pred_svc2 = svc2.predict(train_x_sc)
test_pred_svc2 = svc2.predict(test_x)

In [116]:
print("Training Accuracy : ", accuracy_score(train_pred_svc2,train_y))
print("Testing Accuracy : ",accuracy_score(test_pred_svc2,test_y))

Training Accuracy :  0.8517901017901018
Testing Accuracy :  0.23308424608455316


In [112]:
#overfitted at both c = 0.5 and c = 10