In [19]:
import numpy as np

In [20]:
x1 = np.arange(1,11)
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
x1.shape

(10,)

In [22]:
test_size = 0.20

In [23]:
no_ele = int(x1.shape[0]*(test_size))
no_ele

2

In [24]:
train_size = 10-no_ele
train_data = x1[:train_size]
test_data = x1[train_size:]

In [25]:
train_data

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
test_data

array([ 9, 10])

In [27]:
x2 = x1

In [28]:
x2 = np.random.shuffle(x1)

In [29]:
x1

array([ 3,  4,  9,  6,  8,  1,  7,  5, 10,  2])

In [30]:
x2

In [31]:
train_size = 10-no_ele
train_data = x1[:train_size]
test_data = x1[train_size:]

In [32]:
x1

array([ 3,  4,  9,  6,  8,  1,  7,  5, 10,  2])

In [33]:
train_data

array([3, 4, 9, 6, 8, 1, 7, 5])

In [34]:
test_data

array([10,  2])